services:
  terse-cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terse-cms
    restart: unless-stopped
    env_file: '.env'
    ports:
      - '3000:3000'
    volumes:
    # Mount external repos into the container here
    #  - ./myRepo:/cms/repos/myRepo
