services:
  terse-cms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terse-cms
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./myDir:/cms/files
    # environment:
    # Example of how to pass other variables from your host .env file
    # S3_BUCKET: ${S3_BUCKET}
    # S3_REGION: ${S3_REGION}
    # S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
    # S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    # USE_MOCK_API: ${USE_MOCK_API}
    # GEMINI_API_KEY: ${GEMINI_API_KEY}
